import { BLOCKS } from '../world/Blocks.js';

export const RECIPES = [
  { type: 'shapeless', ingredients: [{ id: BLOCKS.OAK_LOG, count: 1 }], result: { id: BLOCKS.OAK_PLANKS, count: 4 } },
  { type: 'shapeless', ingredients: [{ id: BLOCKS.BIRCH_LOG, count: 1 }], result: { id: BLOCKS.BIRCH_PLANKS, count: 4 } },
  { type: 'shapeless', ingredients: [{ id: BLOCKS.SPRUCE_LOG, count: 1 }], result: { id: BLOCKS.SPRUCE_PLANKS, count: 4 } },
  { type: 'shapeless', ingredients: [{ id: BLOCKS.JUNGLE_LOG, count: 1 }], result: { id: BLOCKS.JUNGLE_PLANKS, count: 4 } },
  { type: 'shapeless', ingredients: [{ id: BLOCKS.ACACIA_LOG, count: 1 }], result: { id: BLOCKS.ACACIA_PLANKS, count: 4 } },
  { type: 'shapeless', ingredients: [{ id: BLOCKS.DARK_OAK_LOG, count: 1 }], result: { id: BLOCKS.DARK_OAK_PLANKS, count: 4 } },
  { type: 'shaped', pattern: [[BLOCKS.OAK_PLANKS],[BLOCKS.OAK_PLANKS]], result: { id: 'stick', count: 4 } },
  { type: 'shaped', pattern: [[BLOCKS.BIRCH_PLANKS],[BLOCKS.BIRCH_PLANKS]], result: { id: 'stick', count: 4 } },
  { type: 'shaped', pattern: [[BLOCKS.SPRUCE_PLANKS],[BLOCKS.SPRUCE_PLANKS]], result: { id: 'stick', count: 4 } },
  { type: 'shaped', pattern: [[BLOCKS.JUNGLE_PLANKS],[BLOCKS.JUNGLE_PLANKS]], result: { id: 'stick', count: 4 } },
  { type: 'shaped', pattern: [[BLOCKS.ACACIA_PLANKS],[BLOCKS.ACACIA_PLANKS]], result: { id: 'stick', count: 4 } },
  { type: 'shaped', pattern: [[BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS],[BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS]], result: { id: BLOCKS.CRAFTING_TABLE, count: 1 } },
  { type: 'shaped', pattern: [['coal'],['stick']], result: { id: BLOCKS.TORCH, count: 4 } },
  // Wool from string
  { type: 'shaped', pattern: [['string','string'],['string','string']], result: { id: BLOCKS.WHITE_WOOL, count: 1 } },
  // Tools
  { type: 'shaped', pattern: [[BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS],[null,'stick',null],[null,'stick',null]], result: { id: 'wooden_pickaxe', count: 1, durability: 59, maxDurability: 59 } },
  { type: 'shaped', pattern: [[BLOCKS.COBBLESTONE, BLOCKS.COBBLESTONE, BLOCKS.COBBLESTONE],[null,'stick',null],[null,'stick',null]], result: { id: 'stone_pickaxe', count: 1, durability: 131, maxDurability: 131 } },
  { type: 'shaped', pattern: [['iron_ingot','iron_ingot','iron_ingot'],[null,'stick',null],[null,'stick',null]], result: { id: 'iron_pickaxe', count: 1, durability: 250, maxDurability: 250 } },
  { type: 'shaped', pattern: [['diamond','diamond','diamond'],[null,'stick',null],[null,'stick',null]], result: { id: 'diamond_pickaxe', count: 1, durability: 1561, maxDurability: 1561 } },
  { type: 'shaped', pattern: [[BLOCKS.OAK_PLANKS],[BLOCKS.OAK_PLANKS],['stick']], result: { id: 'wooden_sword', count: 1, durability: 59, maxDurability: 59 } },
  { type: 'shaped', pattern: [[BLOCKS.COBBLESTONE],[BLOCKS.COBBLESTONE],['stick']], result: { id: 'stone_sword', count: 1, durability: 131, maxDurability: 131 } },
  { type: 'shaped', pattern: [['iron_ingot'],['iron_ingot'],['stick']], result: { id: 'iron_sword', count: 1, durability: 250, maxDurability: 250 } },
  { type: 'shaped', pattern: [['diamond'],['diamond'],['stick']], result: { id: 'diamond_sword', count: 1, durability: 1561, maxDurability: 1561 } },
  { type: 'shaped', pattern: [[BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS],[BLOCKS.OAK_PLANKS,'stick'],[null,'stick']], result: { id: 'wooden_axe', count: 1, durability: 59, maxDurability: 59 } },
  { type: 'shaped', pattern: [[BLOCKS.COBBLESTONE, BLOCKS.COBBLESTONE],[BLOCKS.COBBLESTONE,'stick'],[null,'stick']], result: { id: 'stone_axe', count: 1, durability: 131, maxDurability: 131 } },
  { type: 'shaped', pattern: [['iron_ingot','iron_ingot'],['iron_ingot','stick'],[null,'stick']], result: { id: 'iron_axe', count: 1, durability: 250, maxDurability: 250 } },
  { type: 'shaped', pattern: [['diamond','diamond'],['diamond','stick'],[null,'stick']], result: { id: 'diamond_axe', count: 1, durability: 1561, maxDurability: 1561 } },
  { type: 'shaped', pattern: [[BLOCKS.OAK_PLANKS],['stick'],['stick']], result: { id: 'wooden_shovel', count: 1, durability: 59, maxDurability: 59 } },
  { type: 'shaped', pattern: [[BLOCKS.COBBLESTONE],['stick'],['stick']], result: { id: 'stone_shovel', count: 1, durability: 131, maxDurability: 131 } },
  { type: 'shaped', pattern: [['iron_ingot'],['stick'],['stick']], result: { id: 'iron_shovel', count: 1, durability: 250, maxDurability: 250 } },
  { type: 'shaped', pattern: [['diamond'],['stick'],['stick']], result: { id: 'diamond_shovel', count: 1, durability: 1561, maxDurability: 1561 } },
  { type: 'shaped', pattern: [[BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS],[null,'stick',null],[null,'stick',null]], result: { id: 'wooden_hoe', count: 1, durability: 59, maxDurability: 59 } },
  { type: 'shaped', pattern: [[BLOCKS.COBBLESTONE, BLOCKS.COBBLESTONE],[null,'stick',null],[null,'stick',null]], result: { id: 'stone_hoe', count: 1, durability: 131, maxDurability: 131 } },
  { type: 'shaped', pattern: [['iron_ingot','iron_ingot'],[null,'stick',null],[null,'stick',null]], result: { id: 'iron_hoe', count: 1, durability: 250, maxDurability: 250 } },
  { type: 'shaped', pattern: [[BLOCKS.COBBLESTONE, BLOCKS.COBBLESTONE, BLOCKS.COBBLESTONE],[BLOCKS.COBBLESTONE,null,BLOCKS.COBBLESTONE],[BLOCKS.COBBLESTONE,BLOCKS.COBBLESTONE,BLOCKS.COBBLESTONE]], result: { id: BLOCKS.FURNACE, count: 1 } },
  { type: 'shaped', pattern: [[BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS],[BLOCKS.OAK_PLANKS,null,BLOCKS.OAK_PLANKS],[BLOCKS.OAK_PLANKS,BLOCKS.OAK_PLANKS,BLOCKS.OAK_PLANKS]], result: { id: BLOCKS.CHEST, count: 1 } },
  { type: 'shaped', pattern: [[BLOCKS.STONE,BLOCKS.STONE],[BLOCKS.STONE,BLOCKS.STONE]], result: { id: BLOCKS.STONE_BRICKS, count: 4 } },
  { type: 'shaped', pattern: [[BLOCKS.SAND,BLOCKS.SAND],[BLOCKS.SAND,BLOCKS.SAND]], result: { id: BLOCKS.SANDSTONE, count: 1 } },
  { type: 'shaped', pattern: [['clay_ball','clay_ball'],['clay_ball','clay_ball']], result: { id: BLOCKS.CLAY, count: 1 } },
  { type: 'shaped', pattern: [['brick','brick'],['brick','brick']], result: { id: BLOCKS.BRICKS, count: 1 } },
  { type: 'shaped', pattern: [[BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS],['book','book','book'],[BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS]], result: { id: BLOCKS.BOOKSHELF, count: 1 } },
  { type: 'shaped', pattern: [['glowstone_dust','glowstone_dust'],['glowstone_dust','glowstone_dust']], result: { id: BLOCKS.GLOWSTONE, count: 1 } },
  { type: 'shaped', pattern: [['wheat','wheat','wheat']], result: { id: 'bread', count: 1 } },
  // New building blocks
  { type: 'shaped', pattern: [['iron_ingot','iron_ingot','iron_ingot'],['iron_ingot','iron_ingot','iron_ingot'],['iron_ingot','iron_ingot','iron_ingot']], result: { id: BLOCKS.IRON_BLOCK, count: 1 } },
  { type: 'shapeless', ingredients: [{ id: BLOCKS.IRON_BLOCK, count: 1 }], result: { id: 'iron_ingot', count: 9 } },
  { type: 'shaped', pattern: [['gold_ingot','gold_ingot','gold_ingot'],['gold_ingot','gold_ingot','gold_ingot'],['gold_ingot','gold_ingot','gold_ingot']], result: { id: BLOCKS.GOLD_BLOCK, count: 1 } },
  { type: 'shapeless', ingredients: [{ id: BLOCKS.GOLD_BLOCK, count: 1 }], result: { id: 'gold_ingot', count: 9 } },
  { type: 'shaped', pattern: [['diamond','diamond','diamond'],['diamond','diamond','diamond'],['diamond','diamond','diamond']], result: { id: BLOCKS.DIAMOND_BLOCK, count: 1 } },
  { type: 'shapeless', ingredients: [{ id: BLOCKS.DIAMOND_BLOCK, count: 1 }], result: { id: 'diamond', count: 9 } },
  { type: 'shaped', pattern: [['emerald','emerald','emerald'],['emerald','emerald','emerald'],['emerald','emerald','emerald']], result: { id: BLOCKS.EMERALD_BLOCK, count: 1 } },
  { type: 'shaped', pattern: [['redstone','redstone','redstone'],['redstone','redstone','redstone'],['redstone','redstone','redstone']], result: { id: BLOCKS.REDSTONE_BLOCK, count: 1 } },
  { type: 'shaped', pattern: [['coal','coal','coal'],['coal','coal','coal'],['coal','coal','coal']], result: { id: BLOCKS.COAL_BLOCK, count: 1 } },
  { type: 'shapeless', ingredients: [{ id: BLOCKS.COAL_BLOCK, count: 1 }], result: { id: 'coal', count: 9 } },
  { type: 'shaped', pattern: [['wheat','wheat','wheat'],['wheat','wheat','wheat'],['wheat','wheat','wheat']], result: { id: BLOCKS.HAY_BLOCK, count: 1 } },
  { type: 'shapeless', ingredients: [{ id: BLOCKS.HAY_BLOCK, count: 1 }], result: { id: 'wheat', count: 9 } },
  { type: 'shaped', pattern: [[BLOCKS.SAND,BLOCKS.SAND,BLOCKS.SAND],[BLOCKS.SAND,BLOCKS.SAND,BLOCKS.SAND],[BLOCKS.SAND,BLOCKS.SAND,BLOCKS.SAND]], result: { id: BLOCKS.SMOOTH_SANDSTONE, count: 1 } },
  { type: 'shaped', pattern: [[BLOCKS.WHITE_WOOL, BLOCKS.WHITE_WOOL],[BLOCKS.WHITE_WOOL, BLOCKS.WHITE_WOOL]], result: { id: BLOCKS.WHITE_TERRACOTTA, count: 1 } },
  { type: 'shaped', pattern: [[BLOCKS.GRANITE],[BLOCKS.GRANITE]], result: { id: BLOCKS.POLISHED_GRANITE, count: 1 } },
  { type: 'shaped', pattern: [[BLOCKS.DIORITE],[BLOCKS.DIORITE]], result: { id: BLOCKS.POLISHED_DIORITE, count: 1 } },
  { type: 'shaped', pattern: [[BLOCKS.ANDESITE],[BLOCKS.ANDESITE]], result: { id: BLOCKS.POLISHED_ANDESITE, count: 1 } },
  { type: 'shaped', pattern: [[BLOCKS.STONE],[BLOCKS.STONE]], result: { id: BLOCKS.SMOOTH_STONE, count: 1 } },
  { type: 'shaped', pattern: [['string','string','string'],['string','string','string'],['string','string','string']], result: { id: BLOCKS.WHITE_WOOL, count: 1 } },
  // Slabs
  { type: 'shaped', pattern: [[BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS, BLOCKS.OAK_PLANKS]], result: { id: BLOCKS.OAK_SLAB, count: 6 } },
  { type: 'shaped', pattern: [[BLOCKS.STONE, BLOCKS.STONE, BLOCKS.STONE]], result: { id: BLOCKS.STONE_SLAB, count: 6 } },
  { type: 'shaped', pattern: [[BLOCKS.COBBLESTONE, BLOCKS.COBBLESTONE, BLOCKS.COBBLESTONE]], result: { id: BLOCKS.COBBLESTONE_SLAB, count: 6 } },
  // Fence
  { type: 'shaped', pattern: [[BLOCKS.OAK_PLANKS,'stick',BLOCKS.OAK_PLANKS],[BLOCKS.OAK_PLANKS,'stick',BLOCKS.OAK_PLANKS]], result: { id: BLOCKS.OAK_FENCE, count: 3 } },
  // Paper -> book
  { type: 'shaped', pattern: [['string','string','string']], result: { id: 'book', count: 1 } },
  // Ladder
  { type: 'shaped', pattern: [['stick',null,'stick'],['stick','stick','stick'],['stick',null,'stick']], result: { id: BLOCKS.IRON_BARS, count: 16 } },
  // Bow
  { type: 'shaped', pattern: [[null,'stick','string'],['stick',null,'string'],[null,'stick','string']], result: { id: 'bow', count: 1 } },
  { type: 'shaped', pattern: [['string','string','string']], result: { id: 'arrow', count: 4 } },
  // Shears
  { type: 'shaped', pattern: [['iron_ingot',null], [null,'iron_ingot']], result: { id: 'shears', count: 1, durability: 238, maxDurability: 238 } },
];
