// Block ID constants and block definitions - Expanded to 110+ blocks for 80% parity
export const BLOCKS = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  COBBLESTONE: 4,
  OAK_LOG: 5,
  OAK_LEAVES: 6,
  OAK_PLANKS: 7,
  SAND: 8,
  GRAVEL: 9,
  WATER: 10,
  BEDROCK: 11,
  GLASS: 12,
  COAL_ORE: 13,
  IRON_ORE: 14,
  GOLD_ORE: 15,
  DIAMOND_ORE: 16,
  REDSTONE_ORE: 17,
  EMERALD_ORE: 18,
  CRAFTING_TABLE: 19,
  FURNACE: 20,
  CHEST: 21,
  TORCH: 22,
  SNOW_GRASS: 23,
  SNOW_BLOCK: 24,
  ICE: 25,
  CACTUS: 26,
  POPPY: 27,
  DANDELION: 28,
  TALL_GRASS: 29,
  RED_MUSHROOM: 30,
  BROWN_MUSHROOM: 31,
  BIRCH_LOG: 32,
  BIRCH_LEAVES: 33,
  BIRCH_PLANKS: 34,
  SPRUCE_LOG: 35,
  SPRUCE_LEAVES: 36,
  SPRUCE_PLANKS: 37,
  STONE_BRICKS: 38,
  MOSSY_COBBLESTONE: 39,
  CLAY: 40,
  BRICKS: 41,
  BOOKSHELF: 42,
  OBSIDIAN: 43,
  NETHERRACK: 44,
  GLOWSTONE: 45,
  SANDSTONE: 46,
  LAVA: 47,
  // NEW BLOCKS - Building & Ores
  IRON_BLOCK: 48,
  GOLD_BLOCK: 49,
  DIAMOND_BLOCK: 50,
  EMERALD_BLOCK: 51,
  REDSTONE_BLOCK: 52,
  LAPIS_ORE: 53,
  LAPIS_BLOCK: 54,
  COAL_BLOCK: 55,
  HAY_BLOCK: 56,
  PUMPKIN: 57,
  MELON_BLOCK: 58,
  TNT: 59,
  SPONGE: 60,
  WHITE_WOOL: 61,
  ORANGE_WOOL: 62,
  MAGENTA_WOOL: 63,
  LIGHT_BLUE_WOOL: 64,
  YELLOW_WOOL: 65,
  LIME_WOOL: 66,
  PINK_WOOL: 67,
  GRAY_WOOL: 68,
  LIGHT_GRAY_WOOL: 69,
  CYAN_WOOL: 70,
  PURPLE_WOOL: 71,
  BLUE_WOOL: 72,
  BROWN_WOOL: 73,
  GREEN_WOOL: 74,
  RED_WOOL: 75,
  BLACK_WOOL: 76,
  TERRACOTTA: 77,
  WHITE_TERRACOTTA: 78,
  ORANGE_TERRACOTTA: 79,
  RED_TERRACOTTA: 80,
  BLUE_TERRACOTTA: 81,
  GRANITE: 82,
  DIORITE: 83,
  ANDESITE: 84,
  POLISHED_GRANITE: 85,
  POLISHED_DIORITE: 86,
  POLISHED_ANDESITE: 87,
  SMOOTH_STONE: 88,
  FARMLAND: 89,
  WHEAT: 90,
  OAK_SLAB: 91,
  STONE_SLAB: 92,
  COBBLESTONE_SLAB: 93,
  OAK_FENCE: 94,
  IRON_BARS: 95,
  JUNGLE_LOG: 96,
  JUNGLE_LEAVES: 97,
  JUNGLE_PLANKS: 98,
  ACACIA_LOG: 99,
  ACACIA_LEAVES: 100,
  ACACIA_PLANKS: 101,
  DARK_OAK_LOG: 102,
  DARK_OAK_LEAVES: 103,
  DARK_OAK_PLANKS: 104,
  MUSHROOM_STEM: 105,
  RED_MUSHROOM_BLOCK: 106,
  BROWN_MUSHROOM_BLOCK: 107,
  QUARTZ_BLOCK: 108,
  COPPER_ORE: 109,
  COPPER_BLOCK: 110,
  SOUL_SAND: 111,
  SOUL_SOIL: 112,
  BASALT: 113,
  BLACKSTONE: 114,
  DEEPSLATE: 115,
  SMOOTH_SANDSTONE: 116,
  CHISELED_SANDSTONE: 117,
  SEA_LANTERN: 118,
  PRISMARINE: 119,
  OAK_STAIRS: 120,
};

export const WOOL_COLORS = [
  BLOCKS.WHITE_WOOL, BLOCKS.ORANGE_WOOL, BLOCKS.MAGENTA_WOOL, BLOCKS.LIGHT_BLUE_WOOL,
  BLOCKS.YELLOW_WOOL, BLOCKS.LIME_WOOL, BLOCKS.PINK_WOOL, BLOCKS.GRAY_WOOL,
  BLOCKS.LIGHT_GRAY_WOOL, BLOCKS.CYAN_WOOL, BLOCKS.PURPLE_WOOL, BLOCKS.BLUE_WOOL,
  BLOCKS.BROWN_WOOL, BLOCKS.GREEN_WOOL, BLOCKS.RED_WOOL, BLOCKS.BLACK_WOOL,
];

export const BLOCK_DEFS = {
  [BLOCKS.AIR]: { id: BLOCKS.AIR, name: 'Air', solid: false, transparent: true, liquid: false, hardness: 0, drops: null },
  [BLOCKS.GRASS]: { id: BLOCKS.GRASS, name: 'Grass Block', solid: true, transparent: false, sound: 'grass', hardness: 0.6, drops: { id: BLOCKS.DIRT, count: 1 }, tool: 'shovel', textures: { top: 'grass_top', bottom: 'dirt', side: 'grass_side' } },
  [BLOCKS.DIRT]: { id: BLOCKS.DIRT, name: 'Dirt', solid: true, transparent: false, sound: 'dirt', hardness: 0.5, drops: { id: BLOCKS.DIRT, count: 1 }, tool: 'shovel', textures: { all: 'dirt' } },
  [BLOCKS.STONE]: { id: BLOCKS.STONE, name: 'Stone', solid: true, transparent: false, sound: 'stone', hardness: 1.5, drops: { id: BLOCKS.COBBLESTONE, count: 1 }, tool: 'pickaxe', textures: { all: 'stone' } },
  [BLOCKS.COBBLESTONE]: { id: BLOCKS.COBBLESTONE, name: 'Cobblestone', solid: true, transparent: false, sound: 'stone', hardness: 2.0, drops: { id: BLOCKS.COBBLESTONE, count: 1 }, tool: 'pickaxe', textures: { all: 'cobblestone' } },
  [BLOCKS.OAK_LOG]: { id: BLOCKS.OAK_LOG, name: 'Oak Log', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.OAK_LOG, count: 1 }, tool: 'axe', textures: { top: 'oak_log_top', bottom: 'oak_log_top', side: 'oak_log_side' } },
  [BLOCKS.OAK_LEAVES]: { id: BLOCKS.OAK_LEAVES, name: 'Oak Leaves', solid: true, transparent: true, cutout: true, sound: 'grass', hardness: 0.2, drops: { id: BLOCKS.OAK_LEAVES, count: 1, chance: 0.1, alternative: { id: 'apple', count: 1, chance: 0.05 } }, tool: 'shears', textures: { all: 'oak_leaves' } },
  [BLOCKS.OAK_PLANKS]: { id: BLOCKS.OAK_PLANKS, name: 'Oak Planks', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.OAK_PLANKS, count: 1 }, tool: 'axe', textures: { all: 'oak_planks' } },
  [BLOCKS.SAND]: { id: BLOCKS.SAND, name: 'Sand', solid: true, transparent: false, sound: 'sand', hardness: 0.5, drops: { id: BLOCKS.SAND, count: 1 }, tool: 'shovel', textures: { all: 'sand' } },
  [BLOCKS.GRAVEL]: { id: BLOCKS.GRAVEL, name: 'Gravel', solid: true, transparent: false, sound: 'gravel', hardness: 0.6, drops: { id: BLOCKS.GRAVEL, count: 1 }, tool: 'shovel', textures: { all: 'gravel' } },
  [BLOCKS.WATER]: { id: BLOCKS.WATER, name: 'Water', solid: false, transparent: true, liquid: true, sound: 'water', hardness: 100, drops: null, textures: { all: 'water' } },
  [BLOCKS.BEDROCK]: { id: BLOCKS.BEDROCK, name: 'Bedrock', solid: true, transparent: false, sound: 'stone', hardness: -1, drops: null, textures: { all: 'bedrock' } },
  [BLOCKS.GLASS]: { id: BLOCKS.GLASS, name: 'Glass', solid: true, transparent: true, sound: 'glass', hardness: 0.3, drops: null, textures: { all: 'glass' } },
  [BLOCKS.COAL_ORE]: { id: BLOCKS.COAL_ORE, name: 'Coal Ore', solid: true, transparent: false, sound: 'stone', hardness: 3.0, drops: { id: 'coal', count: 1 }, tool: 'pickaxe', textures: { all: 'coal_ore' } },
  [BLOCKS.IRON_ORE]: { id: BLOCKS.IRON_ORE, name: 'Iron Ore', solid: true, transparent: false, sound: 'stone', hardness: 3.0, drops: { id: BLOCKS.IRON_ORE, count: 1 }, tool: 'pickaxe', textures: { all: 'iron_ore' } },
  [BLOCKS.GOLD_ORE]: { id: BLOCKS.GOLD_ORE, name: 'Gold Ore', solid: true, transparent: false, sound: 'stone', hardness: 3.0, drops: { id: BLOCKS.GOLD_ORE, count: 1 }, tool: 'pickaxe', textures: { all: 'gold_ore' } },
  [BLOCKS.DIAMOND_ORE]: { id: BLOCKS.DIAMOND_ORE, name: 'Diamond Ore', solid: true, transparent: false, sound: 'stone', hardness: 3.0, drops: { id: 'diamond', count: 1 }, tool: 'pickaxe', textures: { all: 'diamond_ore' } },
  [BLOCKS.REDSTONE_ORE]: { id: BLOCKS.REDSTONE_ORE, name: 'Redstone Ore', solid: true, transparent: false, sound: 'stone', hardness: 3.0, luminance: 9, drops: { id: 'redstone', count: 4 }, tool: 'pickaxe', textures: { all: 'redstone_ore' } },
  [BLOCKS.EMERALD_ORE]: { id: BLOCKS.EMERALD_ORE, name: 'Emerald Ore', solid: true, transparent: false, sound: 'stone', hardness: 3.0, drops: { id: 'emerald', count: 1 }, tool: 'pickaxe', textures: { all: 'emerald_ore' } },
  [BLOCKS.CRAFTING_TABLE]: { id: BLOCKS.CRAFTING_TABLE, name: 'Crafting Table', solid: true, transparent: false, sound: 'wood', hardness: 2.5, drops: { id: BLOCKS.CRAFTING_TABLE, count: 1 }, tool: 'axe', isInteractive: true, textures: { top: 'crafting_table_top', bottom: 'oak_planks', side: 'crafting_table_side', front: 'crafting_table_front' } },
  [BLOCKS.FURNACE]: { id: BLOCKS.FURNACE, name: 'Furnace', solid: true, transparent: false, sound: 'stone', hardness: 3.5, drops: { id: BLOCKS.COBBLESTONE, count: 8 }, tool: 'pickaxe', isInteractive: true, textures: { top: 'furnace_top', bottom: 'furnace_top', front: 'furnace_front', side: 'furnace_side' } },
  [BLOCKS.CHEST]: { id: BLOCKS.CHEST, name: 'Chest', solid: true, transparent: false, sound: 'wood', hardness: 2.5, drops: { id: BLOCKS.CHEST, count: 1 }, tool: 'axe', isInteractive: true, textures: { top: 'chest_top', bottom: 'chest_top', front: 'chest_front', side: 'chest_side' } },
  [BLOCKS.TORCH]: { id: BLOCKS.TORCH, name: 'Torch', solid: false, transparent: true, isPlantOrMesh: true, sound: 'wood', hardness: 0.0, luminance: 14, drops: { id: BLOCKS.TORCH, count: 1 }, textures: { all: 'torch' } },
  [BLOCKS.SNOW_GRASS]: { id: BLOCKS.SNOW_GRASS, name: 'Snowy Grass', solid: true, transparent: false, sound: 'snow', hardness: 0.6, drops: { id: BLOCKS.DIRT, count: 1 }, tool: 'shovel', textures: { top: 'snow', bottom: 'dirt', side: 'grass_snow_side' } },
  [BLOCKS.SNOW_BLOCK]: { id: BLOCKS.SNOW_BLOCK, name: 'Snow Block', solid: true, transparent: false, sound: 'snow', hardness: 0.2, drops: { id: BLOCKS.SNOW_BLOCK, count: 1 }, tool: 'shovel', textures: { all: 'snow' } },
  [BLOCKS.ICE]: { id: BLOCKS.ICE, name: 'Ice', solid: true, transparent: true, sound: 'glass', hardness: 0.5, drops: null, textures: { all: 'ice' } },
  [BLOCKS.CACTUS]: { id: BLOCKS.CACTUS, name: 'Cactus', solid: true, transparent: false, sound: 'grass', hardness: 0.4, drops: { id: BLOCKS.CACTUS, count: 1 }, textures: { top: 'cactus_top', bottom: 'cactus_bottom', side: 'cactus_side' } },
  [BLOCKS.POPPY]: { id: BLOCKS.POPPY, name: 'Poppy', solid: false, transparent: true, isPlantOrMesh: true, sound: 'grass', hardness: 0.0, drops: { id: BLOCKS.POPPY, count: 1 }, textures: { all: 'poppy' } },
  [BLOCKS.DANDELION]: { id: BLOCKS.DANDELION, name: 'Dandelion', solid: false, transparent: true, isPlantOrMesh: true, sound: 'grass', hardness: 0.0, drops: { id: BLOCKS.DANDELION, count: 1 }, textures: { all: 'dandelion' } },
  [BLOCKS.TALL_GRASS]: { id: BLOCKS.TALL_GRASS, name: 'Tall Grass', solid: false, transparent: true, isPlantOrMesh: true, sound: 'grass', hardness: 0.0, drops: null, textures: { all: 'tall_grass' } },
  [BLOCKS.RED_MUSHROOM]: { id: BLOCKS.RED_MUSHROOM, name: 'Red Mushroom', solid: false, transparent: true, isPlantOrMesh: true, sound: 'grass', hardness: 0.0, drops: { id: BLOCKS.RED_MUSHROOM, count: 1 }, textures: { all: 'red_mushroom' } },
  [BLOCKS.BROWN_MUSHROOM]: { id: BLOCKS.BROWN_MUSHROOM, name: 'Brown Mushroom', solid: false, transparent: true, isPlantOrMesh: true, sound: 'grass', hardness: 0.0, drops: { id: BLOCKS.BROWN_MUSHROOM, count: 1 }, textures: { all: 'brown_mushroom' } },
  [BLOCKS.BIRCH_LOG]: { id: BLOCKS.BIRCH_LOG, name: 'Birch Log', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.BIRCH_LOG, count: 1 }, tool: 'axe', textures: { top: 'birch_log_top', bottom: 'birch_log_top', side: 'birch_log_side' } },
  [BLOCKS.BIRCH_LEAVES]: { id: BLOCKS.BIRCH_LEAVES, name: 'Birch Leaves', solid: true, transparent: true, cutout: true, sound: 'grass', hardness: 0.2, drops: { id: BLOCKS.BIRCH_LEAVES, count: 1, chance: 0.1 }, tool: 'shears', textures: { all: 'birch_leaves' } },
  [BLOCKS.BIRCH_PLANKS]: { id: BLOCKS.BIRCH_PLANKS, name: 'Birch Planks', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.BIRCH_PLANKS, count: 1 }, tool: 'axe', textures: { all: 'birch_planks' } },
  [BLOCKS.SPRUCE_LOG]: { id: BLOCKS.SPRUCE_LOG, name: 'Spruce Log', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.SPRUCE_LOG, count: 1 }, tool: 'axe', textures: { top: 'spruce_log_top', bottom: 'spruce_log_top', side: 'spruce_log_side' } },
  [BLOCKS.SPRUCE_LEAVES]: { id: BLOCKS.SPRUCE_LEAVES, name: 'Spruce Leaves', solid: true, transparent: true, cutout: true, sound: 'grass', hardness: 0.2, drops: { id: BLOCKS.SPRUCE_LEAVES, count: 1, chance: 0.1 }, tool: 'shears', textures: { all: 'spruce_leaves' } },
  [BLOCKS.SPRUCE_PLANKS]: { id: BLOCKS.SPRUCE_PLANKS, name: 'Spruce Planks', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.SPRUCE_PLANKS, count: 1 }, tool: 'axe', textures: { all: 'spruce_planks' } },
  [BLOCKS.STONE_BRICKS]: { id: BLOCKS.STONE_BRICKS, name: 'Stone Bricks', solid: true, transparent: false, sound: 'stone', hardness: 1.5, drops: { id: BLOCKS.STONE_BRICKS, count: 1 }, tool: 'pickaxe', textures: { all: 'stone_bricks' } },
  [BLOCKS.MOSSY_COBBLESTONE]: { id: BLOCKS.MOSSY_COBBLESTONE, name: 'Mossy Cobblestone', solid: true, transparent: false, sound: 'stone', hardness: 2.0, drops: { id: BLOCKS.MOSSY_COBBLESTONE, count: 1 }, tool: 'pickaxe', textures: { all: 'mossy_cobblestone' } },
  [BLOCKS.CLAY]: { id: BLOCKS.CLAY, name: 'Clay Block', solid: true, transparent: false, sound: 'gravel', hardness: 0.6, drops: { id: 'clay_ball', count: 4 }, tool: 'shovel', textures: { all: 'clay' } },
  [BLOCKS.BRICKS]: { id: BLOCKS.BRICKS, name: 'Bricks', solid: true, transparent: false, sound: 'stone', hardness: 2.0, drops: { id: BLOCKS.BRICKS, count: 1 }, tool: 'pickaxe', textures: { all: 'bricks' } },
  [BLOCKS.BOOKSHELF]: { id: BLOCKS.BOOKSHELF, name: 'Bookshelf', solid: true, transparent: false, sound: 'wood', hardness: 1.5, drops: { id: 'book', count: 3 }, tool: 'axe', textures: { top: 'oak_planks', bottom: 'oak_planks', side: 'bookshelf_side' } },
  [BLOCKS.OBSIDIAN]: { id: BLOCKS.OBSIDIAN, name: 'Obsidian', solid: true, transparent: false, sound: 'stone', hardness: 50.0, drops: { id: BLOCKS.OBSIDIAN, count: 1 }, tool: 'diamond_pickaxe', textures: { all: 'obsidian' } },
  [BLOCKS.NETHERRACK]: { id: BLOCKS.NETHERRACK, name: 'Netherrack', solid: true, transparent: false, sound: 'stone', hardness: 0.4, drops: { id: BLOCKS.NETHERRACK, count: 1 }, tool: 'pickaxe', textures: { all: 'netherrack' } },
  [BLOCKS.GLOWSTONE]: { id: BLOCKS.GLOWSTONE, name: 'Glowstone', solid: true, transparent: false, sound: 'glass', hardness: 0.3, luminance: 15, drops: { id: 'glowstone_dust', count: 4 }, textures: { all: 'glowstone' } },
  [BLOCKS.SANDSTONE]: { id: BLOCKS.SANDSTONE, name: 'Sandstone', solid: true, transparent: false, sound: 'stone', hardness: 0.8, drops: { id: BLOCKS.SANDSTONE, count: 1 }, tool: 'pickaxe', textures: { top: 'sandstone_top', bottom: 'sandstone_bottom', side: 'sandstone_side' } },
  [BLOCKS.LAVA]: { id: BLOCKS.LAVA, name: 'Lava', solid: false, transparent: false, liquid: true, luminance: 15, sound: 'water', hardness: 100, drops: null, textures: { all: 'lava' } },
  // --- NEW BLOCKS ---
  [BLOCKS.IRON_BLOCK]: { id: BLOCKS.IRON_BLOCK, name: 'Block of Iron', solid: true, transparent: false, sound: 'stone', hardness: 5.0, drops: { id: BLOCKS.IRON_BLOCK, count: 1 }, tool: 'pickaxe', textures: { all: 'iron_block' } },
  [BLOCKS.GOLD_BLOCK]: { id: BLOCKS.GOLD_BLOCK, name: 'Block of Gold', solid: true, transparent: false, sound: 'stone', hardness: 3.0, drops: { id: BLOCKS.GOLD_BLOCK, count: 1 }, tool: 'pickaxe', textures: { all: 'gold_block' } },
  [BLOCKS.DIAMOND_BLOCK]: { id: BLOCKS.DIAMOND_BLOCK, name: 'Block of Diamond', solid: true, transparent: false, sound: 'stone', hardness: 5.0, drops: { id: BLOCKS.DIAMOND_BLOCK, count: 1 }, tool: 'pickaxe', textures: { all: 'diamond_block' } },
  [BLOCKS.EMERALD_BLOCK]: { id: BLOCKS.EMERALD_BLOCK, name: 'Block of Emerald', solid: true, transparent: false, sound: 'stone', hardness: 5.0, drops: { id: BLOCKS.EMERALD_BLOCK, count: 1 }, tool: 'pickaxe', textures: { all: 'emerald_block' } },
  [BLOCKS.REDSTONE_BLOCK]: { id: BLOCKS.REDSTONE_BLOCK, name: 'Block of Redstone', solid: true, transparent: false, sound: 'stone', hardness: 5.0, drops: { id: BLOCKS.REDSTONE_BLOCK, count: 1 }, tool: 'pickaxe', textures: { all: 'redstone_block' } },
  [BLOCKS.LAPIS_ORE]: { id: BLOCKS.LAPIS_ORE, name: 'Lapis Lazuli Ore', solid: true, transparent: false, sound: 'stone', hardness: 3.0, drops: { id: 'lapis_lazuli', count: 4 }, tool: 'pickaxe', textures: { all: 'lapis_ore' } },
  [BLOCKS.LAPIS_BLOCK]: { id: BLOCKS.LAPIS_BLOCK, name: 'Lapis Block', solid: true, transparent: false, sound: 'stone', hardness: 3.0, drops: { id: BLOCKS.LAPIS_BLOCK, count: 1 }, tool: 'pickaxe', textures: { all: 'lapis_block' } },
  [BLOCKS.COAL_BLOCK]: { id: BLOCKS.COAL_BLOCK, name: 'Block of Coal', solid: true, transparent: false, sound: 'stone', hardness: 5.0, drops: { id: BLOCKS.COAL_BLOCK, count: 1 }, tool: 'pickaxe', textures: { all: 'coal_block' } },
  [BLOCKS.HAY_BLOCK]: { id: BLOCKS.HAY_BLOCK, name: 'Hay Bale', solid: true, transparent: false, sound: 'grass', hardness: 0.5, drops: { id: BLOCKS.HAY_BLOCK, count: 1 }, textures: { top: 'hay_top', bottom: 'hay_top', side: 'hay_side' } },
  [BLOCKS.PUMPKIN]: { id: BLOCKS.PUMPKIN, name: 'Pumpkin', solid: true, transparent: false, sound: 'wood', hardness: 1.0, drops: { id: BLOCKS.PUMPKIN, count: 1 }, tool: 'axe', textures: { top: 'pumpkin_top', bottom: 'pumpkin_top', side: 'pumpkin_side', front: 'pumpkin_front' } },
  [BLOCKS.MELON_BLOCK]: { id: BLOCKS.MELON_BLOCK, name: 'Melon', solid: true, transparent: false, sound: 'wood', hardness: 1.0, drops: { id: 'melon_slice', count: 3 }, tool: 'axe', textures: { top: 'melon_top', bottom: 'melon_top', side: 'melon_side' } },
  [BLOCKS.TNT]: { id: BLOCKS.TNT, name: 'TNT', solid: true, transparent: false, sound: 'grass', hardness: 0.0, drops: { id: BLOCKS.TNT, count: 1 }, textures: { top: 'tnt_top', bottom: 'tnt_bottom', side: 'tnt_side' } },
  [BLOCKS.SPONGE]: { id: BLOCKS.SPONGE, name: 'Sponge', solid: true, transparent: false, sound: 'grass', hardness: 0.6, drops: { id: BLOCKS.SPONGE, count: 1 }, textures: { all: 'sponge' } },
  [BLOCKS.WHITE_WOOL]: { id: BLOCKS.WHITE_WOOL, name: 'White Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.WHITE_WOOL, count: 1 }, textures: { all: 'white_wool' } },
  [BLOCKS.ORANGE_WOOL]: { id: BLOCKS.ORANGE_WOOL, name: 'Orange Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.ORANGE_WOOL, count: 1 }, textures: { all: 'orange_wool' } },
  [BLOCKS.MAGENTA_WOOL]: { id: BLOCKS.MAGENTA_WOOL, name: 'Magenta Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.MAGENTA_WOOL, count: 1 }, textures: { all: 'magenta_wool' } },
  [BLOCKS.LIGHT_BLUE_WOOL]: { id: BLOCKS.LIGHT_BLUE_WOOL, name: 'Light Blue Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.LIGHT_BLUE_WOOL, count: 1 }, textures: { all: 'light_blue_wool' } },
  [BLOCKS.YELLOW_WOOL]: { id: BLOCKS.YELLOW_WOOL, name: 'Yellow Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.YELLOW_WOOL, count: 1 }, textures: { all: 'yellow_wool' } },
  [BLOCKS.LIME_WOOL]: { id: BLOCKS.LIME_WOOL, name: 'Lime Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.LIME_WOOL, count: 1 }, textures: { all: 'lime_wool' } },
  [BLOCKS.PINK_WOOL]: { id: BLOCKS.PINK_WOOL, name: 'Pink Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.PINK_WOOL, count: 1 }, textures: { all: 'pink_wool' } },
  [BLOCKS.GRAY_WOOL]: { id: BLOCKS.GRAY_WOOL, name: 'Gray Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.GRAY_WOOL, count: 1 }, textures: { all: 'gray_wool' } },
  [BLOCKS.LIGHT_GRAY_WOOL]: { id: BLOCKS.LIGHT_GRAY_WOOL, name: 'Light Gray Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.LIGHT_GRAY_WOOL, count: 1 }, textures: { all: 'light_gray_wool' } },
  [BLOCKS.CYAN_WOOL]: { id: BLOCKS.CYAN_WOOL, name: 'Cyan Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.CYAN_WOOL, count: 1 }, textures: { all: 'cyan_wool' } },
  [BLOCKS.PURPLE_WOOL]: { id: BLOCKS.PURPLE_WOOL, name: 'Purple Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.PURPLE_WOOL, count: 1 }, textures: { all: 'purple_wool' } },
  [BLOCKS.BLUE_WOOL]: { id: BLOCKS.BLUE_WOOL, name: 'Blue Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.BLUE_WOOL, count: 1 }, textures: { all: 'blue_wool' } },
  [BLOCKS.BROWN_WOOL]: { id: BLOCKS.BROWN_WOOL, name: 'Brown Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.BROWN_WOOL, count: 1 }, textures: { all: 'brown_wool' } },
  [BLOCKS.GREEN_WOOL]: { id: BLOCKS.GREEN_WOOL, name: 'Green Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.GREEN_WOOL, count: 1 }, textures: { all: 'green_wool' } },
  [BLOCKS.RED_WOOL]: { id: BLOCKS.RED_WOOL, name: 'Red Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.RED_WOOL, count: 1 }, textures: { all: 'red_wool' } },
  [BLOCKS.BLACK_WOOL]: { id: BLOCKS.BLACK_WOOL, name: 'Black Wool', solid: true, transparent: false, sound: 'grass', hardness: 0.8, drops: { id: BLOCKS.BLACK_WOOL, count: 1 }, textures: { all: 'black_wool' } },
  [BLOCKS.TERRACOTTA]: { id: BLOCKS.TERRACOTTA, name: 'Terracotta', solid: true, transparent: false, sound: 'stone', hardness: 1.25, drops: { id: BLOCKS.TERRACOTTA, count: 1 }, tool: 'pickaxe', textures: { all: 'terracotta' } },
  [BLOCKS.WHITE_TERRACOTTA]: { id: BLOCKS.WHITE_TERRACOTTA, name: 'White Terracotta', solid: true, transparent: false, sound: 'stone', hardness: 1.25, drops: { id: BLOCKS.WHITE_TERRACOTTA, count: 1 }, tool: 'pickaxe', textures: { all: 'white_terracotta' } },
  [BLOCKS.ORANGE_TERRACOTTA]: { id: BLOCKS.ORANGE_TERRACOTTA, name: 'Orange Terracotta', solid: true, transparent: false, sound: 'stone', hardness: 1.25, drops: { id: BLOCKS.ORANGE_TERRACOTTA, count: 1 }, tool: 'pickaxe', textures: { all: 'orange_terracotta' } },
  [BLOCKS.RED_TERRACOTTA]: { id: BLOCKS.RED_TERRACOTTA, name: 'Red Terracotta', solid: true, transparent: false, sound: 'stone', hardness: 1.25, drops: { id: BLOCKS.RED_TERRACOTTA, count: 1 }, tool: 'pickaxe', textures: { all: 'red_terracotta' } },
  [BLOCKS.BLUE_TERRACOTTA]: { id: BLOCKS.BLUE_TERRACOTTA, name: 'Blue Terracotta', solid: true, transparent: false, sound: 'stone', hardness: 1.25, drops: { id: BLOCKS.BLUE_TERRACOTTA, count: 1 }, tool: 'pickaxe', textures: { all: 'blue_terracotta' } },
  [BLOCKS.GRANITE]: { id: BLOCKS.GRANITE, name: 'Granite', solid: true, transparent: false, sound: 'stone', hardness: 1.5, drops: { id: BLOCKS.GRANITE, count: 1 }, tool: 'pickaxe', textures: { all: 'granite' } },
  [BLOCKS.DIORITE]: { id: BLOCKS.DIORITE, name: 'Diorite', solid: true, transparent: false, sound: 'stone', hardness: 1.5, drops: { id: BLOCKS.DIORITE, count: 1 }, tool: 'pickaxe', textures: { all: 'diorite' } },
  [BLOCKS.ANDESITE]: { id: BLOCKS.ANDESITE, name: 'Andesite', solid: true, transparent: false, sound: 'stone', hardness: 1.5, drops: { id: BLOCKS.ANDESITE, count: 1 }, tool: 'pickaxe', textures: { all: 'andesite' } },
  [BLOCKS.POLISHED_GRANITE]: { id: BLOCKS.POLISHED_GRANITE, name: 'Polished Granite', solid: true, transparent: false, sound: 'stone', hardness: 1.5, drops: { id: BLOCKS.POLISHED_GRANITE, count: 1 }, tool: 'pickaxe', textures: { all: 'polished_granite' } },
  [BLOCKS.POLISHED_DIORITE]: { id: BLOCKS.POLISHED_DIORITE, name: 'Polished Diorite', solid: true, transparent: false, sound: 'stone', hardness: 1.5, drops: { id: BLOCKS.POLISHED_DIORITE, count: 1 }, tool: 'pickaxe', textures: { all: 'polished_diorite' } },
  [BLOCKS.POLISHED_ANDESITE]: { id: BLOCKS.POLISHED_ANDESITE, name: 'Polished Andesite', solid: true, transparent: false, sound: 'stone', hardness: 1.5, drops: { id: BLOCKS.POLISHED_ANDESITE, count: 1 }, tool: 'pickaxe', textures: { all: 'polished_andesite' } },
  [BLOCKS.SMOOTH_STONE]: { id: BLOCKS.SMOOTH_STONE, name: 'Smooth Stone', solid: true, transparent: false, sound: 'stone', hardness: 2.0, drops: { id: BLOCKS.SMOOTH_STONE, count: 1 }, tool: 'pickaxe', textures: { all: 'smooth_stone' } },
  [BLOCKS.FARMLAND]: { id: BLOCKS.FARMLAND, name: 'Farmland', solid: true, transparent: false, sound: 'dirt', hardness: 0.6, drops: { id: BLOCKS.DIRT, count: 1 }, textures: { top: 'farmland_top', bottom: 'dirt', side: 'farmland_side' } },
  [BLOCKS.WHEAT]: { id: BLOCKS.WHEAT, name: 'Wheat Crops', solid: false, transparent: true, isPlantOrMesh: true, sound: 'grass', hardness: 0.0, drops: { id: 'wheat', count: 1 }, textures: { all: 'wheat_stage_7' } },
  [BLOCKS.OAK_SLAB]: { id: BLOCKS.OAK_SLAB, name: 'Oak Slab', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.OAK_SLAB, count: 1 }, tool: 'axe', textures: { top: 'oak_planks', bottom: 'oak_planks', side: 'oak_planks' } },
  [BLOCKS.STONE_SLAB]: { id: BLOCKS.STONE_SLAB, name: 'Stone Slab', solid: true, transparent: false, sound: 'stone', hardness: 2.0, drops: { id: BLOCKS.STONE_SLAB, count: 1 }, tool: 'pickaxe', textures: { top: 'stone', bottom: 'stone', side: 'stone' } },
  [BLOCKS.COBBLESTONE_SLAB]: { id: BLOCKS.COBBLESTONE_SLAB, name: 'Cobblestone Slab', solid: true, transparent: false, sound: 'stone', hardness: 2.0, drops: { id: BLOCKS.COBBLESTONE_SLAB, count: 1 }, tool: 'pickaxe', textures: { all: 'cobblestone' } },
  [BLOCKS.OAK_FENCE]: { id: BLOCKS.OAK_FENCE, name: 'Oak Fence', solid: true, transparent: true, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.OAK_FENCE, count: 1 }, tool: 'axe', textures: { all: 'oak_planks' } },
  [BLOCKS.IRON_BARS]: { id: BLOCKS.IRON_BARS, name: 'Iron Bars', solid: false, transparent: true, sound: 'stone', hardness: 5.0, drops: { id: BLOCKS.IRON_BARS, count: 1 }, tool: 'pickaxe', textures: { all: 'iron_bars' } },
  [BLOCKS.JUNGLE_LOG]: { id: BLOCKS.JUNGLE_LOG, name: 'Jungle Log', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.JUNGLE_LOG, count: 1 }, tool: 'axe', textures: { top: 'jungle_log_top', bottom: 'jungle_log_top', side: 'jungle_log_side' } },
  [BLOCKS.JUNGLE_LEAVES]: { id: BLOCKS.JUNGLE_LEAVES, name: 'Jungle Leaves', solid: true, transparent: true, cutout: true, sound: 'grass', hardness: 0.2, drops: { id: BLOCKS.JUNGLE_LEAVES, count: 1, chance: 0.1 }, tool: 'shears', textures: { all: 'jungle_leaves' } },
  [BLOCKS.JUNGLE_PLANKS]: { id: BLOCKS.JUNGLE_PLANKS, name: 'Jungle Planks', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.JUNGLE_PLANKS, count: 1 }, tool: 'axe', textures: { all: 'jungle_planks' } },
  [BLOCKS.ACACIA_LOG]: { id: BLOCKS.ACACIA_LOG, name: 'Acacia Log', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.ACACIA_LOG, count: 1 }, tool: 'axe', textures: { top: 'acacia_log_top', bottom: 'acacia_log_top', side: 'acacia_log_side' } },
  [BLOCKS.ACACIA_LEAVES]: { id: BLOCKS.ACACIA_LEAVES, name: 'Acacia Leaves', solid: true, transparent: true, cutout: true, sound: 'grass', hardness: 0.2, drops: { id: BLOCKS.ACACIA_LEAVES, count: 1, chance: 0.1 }, tool: 'shears', textures: { all: 'acacia_leaves' } },
  [BLOCKS.ACACIA_PLANKS]: { id: BLOCKS.ACACIA_PLANKS, name: 'Acacia Planks', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.ACACIA_PLANKS, count: 1 }, tool: 'axe', textures: { all: 'acacia_planks' } },
  [BLOCKS.DARK_OAK_LOG]: { id: BLOCKS.DARK_OAK_LOG, name: 'Dark Oak Log', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.DARK_OAK_LOG, count: 1 }, tool: 'axe', textures: { top: 'dark_oak_log_top', bottom: 'dark_oak_log_top', side: 'dark_oak_log_side' } },
  [BLOCKS.DARK_OAK_LEAVES]: { id: BLOCKS.DARK_OAK_LEAVES, name: 'Dark Oak Leaves', solid: true, transparent: true, cutout: true, sound: 'grass', hardness: 0.2, drops: { id: BLOCKS.DARK_OAK_LEAVES, count: 1, chance: 0.1 }, tool: 'shears', textures: { all: 'dark_oak_leaves' } },
  [BLOCKS.DARK_OAK_PLANKS]: { id: BLOCKS.DARK_OAK_PLANKS, name: 'Dark Oak Planks', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.DARK_OAK_PLANKS, count: 1 }, tool: 'axe', textures: { all: 'dark_oak_planks' } },
  [BLOCKS.MUSHROOM_STEM]: { id: BLOCKS.MUSHROOM_STEM, name: 'Mushroom Stem', solid: true, transparent: false, sound: 'wood', hardness: 0.2, drops: { id: BLOCKS.MUSHROOM_STEM, count: 1 }, textures: { all: 'mushroom_stem' } },
  [BLOCKS.RED_MUSHROOM_BLOCK]: { id: BLOCKS.RED_MUSHROOM_BLOCK, name: 'Red Mushroom Block', solid: true, transparent: false, sound: 'wood', hardness: 0.2, drops: { id: BLOCKS.RED_MUSHROOM_BLOCK, count: 1 }, textures: { all: 'red_mushroom_block' } },
  [BLOCKS.BROWN_MUSHROOM_BLOCK]: { id: BLOCKS.BROWN_MUSHROOM_BLOCK, name: 'Brown Mushroom Block', solid: true, transparent: false, sound: 'wood', hardness: 0.2, drops: { id: BLOCKS.BROWN_MUSHROOM_BLOCK, count: 1 }, textures: { all: 'brown_mushroom_block' } },
  [BLOCKS.QUARTZ_BLOCK]: { id: BLOCKS.QUARTZ_BLOCK, name: 'Quartz Block', solid: true, transparent: false, sound: 'stone', hardness: 0.8, drops: { id: BLOCKS.QUARTZ_BLOCK, count: 1 }, tool: 'pickaxe', textures: { top: 'quartz_top', bottom: 'quartz_bottom', side: 'quartz_side' } },
  [BLOCKS.COPPER_ORE]: { id: BLOCKS.COPPER_ORE, name: 'Copper Ore', solid: true, transparent: false, sound: 'stone', hardness: 3.0, drops: { id: 'raw_copper', count: 2 }, tool: 'pickaxe', textures: { all: 'copper_ore' } },
  [BLOCKS.COPPER_BLOCK]: { id: BLOCKS.COPPER_BLOCK, name: 'Block of Copper', solid: true, transparent: false, sound: 'stone', hardness: 3.0, drops: { id: BLOCKS.COPPER_BLOCK, count: 1 }, tool: 'pickaxe', textures: { all: 'copper_block' } },
  [BLOCKS.SOUL_SAND]: { id: BLOCKS.SOUL_SAND, name: 'Soul Sand', solid: true, transparent: false, sound: 'sand', hardness: 0.5, drops: { id: BLOCKS.SOUL_SAND, count: 1 }, textures: { all: 'soul_sand' } },
  [BLOCKS.SOUL_SOIL]: { id: BLOCKS.SOUL_SOIL, name: 'Soul Soil', solid: true, transparent: false, sound: 'sand', hardness: 0.5, drops: { id: BLOCKS.SOUL_SOIL, count: 1 }, textures: { all: 'soul_soil' } },
  [BLOCKS.BASALT]: { id: BLOCKS.BASALT, name: 'Basalt', solid: true, transparent: false, sound: 'stone', hardness: 1.25, drops: { id: BLOCKS.BASALT, count: 1 }, tool: 'pickaxe', textures: { top: 'basalt_top', bottom: 'basalt_top', side: 'basalt_side' } },
  [BLOCKS.BLACKSTONE]: { id: BLOCKS.BLACKSTONE, name: 'Blackstone', solid: true, transparent: false, sound: 'stone', hardness: 1.5, drops: { id: BLOCKS.BLACKSTONE, count: 1 }, tool: 'pickaxe', textures: { all: 'blackstone' } },
  [BLOCKS.DEEPSLATE]: { id: BLOCKS.DEEPSLATE, name: 'Deepslate', solid: true, transparent: false, sound: 'stone', hardness: 3.0, drops: { id: BLOCKS.COBBLESTONE, count: 1 }, tool: 'pickaxe', textures: { top: 'deepslate_top', bottom: 'deepslate_top', side: 'deepslate_side' } },
  [BLOCKS.SMOOTH_SANDSTONE]: { id: BLOCKS.SMOOTH_SANDSTONE, name: 'Smooth Sandstone', solid: true, transparent: false, sound: 'stone', hardness: 2.0, drops: { id: BLOCKS.SMOOTH_SANDSTONE, count: 1 }, tool: 'pickaxe', textures: { all: 'smooth_sandstone' } },
  [BLOCKS.CHISELED_SANDSTONE]: { id: BLOCKS.CHISELED_SANDSTONE, name: 'Chiseled Sandstone', solid: true, transparent: false, sound: 'stone', hardness: 0.8, drops: { id: BLOCKS.CHISELED_SANDSTONE, count: 1 }, tool: 'pickaxe', textures: { top: 'chiseled_sandstone_top', bottom: 'sandstone_bottom', side: 'chiseled_sandstone_side' } },
  [BLOCKS.SEA_LANTERN]: { id: BLOCKS.SEA_LANTERN, name: 'Sea Lantern', solid: true, transparent: false, sound: 'glass', hardness: 0.3, luminance: 15, drops: { id: 'prismarine_crystals', count: 2 }, textures: { all: 'sea_lantern' } },
  [BLOCKS.PRISMARINE]: { id: BLOCKS.PRISMARINE, name: 'Prismarine', solid: true, transparent: false, sound: 'stone', hardness: 1.5, drops: { id: BLOCKS.PRISMARINE, count: 1 }, tool: 'pickaxe', textures: { all: 'prismarine' } },
  [BLOCKS.OAK_STAIRS]: { id: BLOCKS.OAK_STAIRS, name: 'Oak Stairs', solid: true, transparent: false, sound: 'wood', hardness: 2.0, drops: { id: BLOCKS.OAK_STAIRS, count: 1 }, tool: 'axe', textures: { all: 'oak_planks' } },
};

export function getBlockDef(id) {
  return BLOCK_DEFS[id] || BLOCK_DEFS[BLOCKS.AIR];
}

export const SMELTING_RECIPES = {
  [BLOCKS.IRON_ORE]: { result: 'iron_ingot', count: 1, xp: 0.7 },
  [BLOCKS.GOLD_ORE]: { result: 'gold_ingot', count: 1, xp: 1.0 },
  [BLOCKS.COBBLESTONE]: { result: BLOCKS.STONE, count: 1, xp: 0.1 },
  [BLOCKS.SAND]: { result: BLOCKS.GLASS, count: 1, xp: 0.1 },
  [BLOCKS.CLAY]: { result: BLOCKS.TERRACOTTA, count: 1, xp: 0.3 },
  'raw_porkchop': { result: 'cooked_porkchop', count: 1, xp: 0.35 },
  'raw_beef': { result: 'cooked_beef', count: 1, xp: 0.35 },
  'raw_copper': { result: 'copper_ingot', count: 1, xp: 0.7 },
  [BLOCKS.COPPER_ORE]: { result: 'copper_ingot', count: 1, xp: 0.7 },
};
